In [1]:
!pip install mlxtend

Collecting mlxtend
  Downloading mlxtend-0.23.1-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: scipy>=1.2.1 in c:\users\anirudh\anaconda3\lib\site-packages (from mlxtend) (1.11.4)
Requirement already satisfied: numpy>=1.16.2 in c:\users\anirudh\anaconda3\lib\site-packages (from mlxtend) (1.24.3)
Requirement already satisfied: pandas>=0.24.2 in c:\users\anirudh\anaconda3\lib\site-packages (from mlxtend) (2.1.4)
Requirement already satisfied: scikit-learn>=1.0.2 in c:\users\anirudh\anaconda3\lib\site-packages (from mlxtend) (1.3.0)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\anirudh\anaconda3\lib\site-packages (from mlxtend) (3.8.0)
Requirement already satisfied: joblib>=0.13.2 in c:\users\anirudh\anaconda3\lib\site-packages (from mlxtend) (1.2.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\anirudh\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\anirudh\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\anirudh\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\anirudh\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\anirudh\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (23.1)
Requirement already satisfied: pillow>=6.2.0 in c:\users\anirudh\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (10.2.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\anirudh\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\anirudh\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\anirudh\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\anirudh\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2023.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\anirudh\anaconda3\lib\site-packages (from scikit-learn>=1.0.2->mlxtend) (2.2.0)
Requirement already satisfied: six>=1.5 in c:\users\anirudh\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)
Downloading mlxtend-0.23.1-py3-none-any.whl (1.4 MB)
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   - -------------------------------------- 0.1/1.4 MB 544.7 kB/s eta 0:00:03
   -- ------------------------------------- 0.1/1.4 MB 651.6 kB/s eta 0:00:03
   ---- ----------------------------------- 0.2/1.4 MB 978.3 kB/s eta 0:00:02
   -------- ------------------------------- 0.3/1.4 MB 1.4 MB/s eta 0:00:01
   ---------- ----------------------------- 0.4/1.4 MB 1.4 MB/s eta 0:00:01
   -------------- ------------------------- 0.5/1.4 MB 1.7 MB/s eta 0:00:01
   ----------------- ---------------------- 0.6/1.4 MB 1.7 MB/s eta 0:00:01
   ------------------- -------------------- 0.7/1.4 MB 1.7 MB/s eta 0:00:01
   --------------------- ------------------ 0.8/1.4 MB 1.6 MB/s eta 0:00:01
   ----------------------- ---------------- 0.9/1.4 MB 1.6 MB/s eta 0:00:01
   ------------------------- -------------- 0.9/1.4 MB 1.6 MB/s eta 0:00:01
   --------------------------- ------------ 1.0/1.4 MB 1.6 MB/s eta 0:00:01
   --------------------------- ------------ 1.0/1.4 MB 1.6 MB/s eta 0:00:01
   ------------------------------ --------- 1.1/1.4 MB 1.6 MB/s eta 0:00:01
   ------------------------------- -------- 1.2/1.4 MB 1.6 MB/s eta 0:00:01
   ----------------------------------- ---- 1.3/1.4 MB 1.6 MB/s eta 0:00:01
   ------------------------------------- -- 1.4/1.4 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------  1.4/1.4 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------  1.4/1.4 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------- 1.4/1.4 MB 1.5 MB/s eta 0:00:00
Installing collected packages: mlxtend
Successfully installed mlxtend-0.23.1

In [2]:
# Import 'pandas' for working with data frames
import pandas as pd

# Import 'matplotlib.pyplot' and 'seaborn' for working with data frames
import matplotlib.pyplot as plt
import seaborn as sns

# Import 'apriori' and 'association_rules' from 'mlxtend'
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [3]:
import warnings
warnings.filterwarnings('ignore')

In [5]:
# Load the data and take a look at it
# Note: The data needs to be in binary matrix format
df1 = pd.read_csv('supermarket_binarymat.csv')
df1.head()

#from the basket all unique names are taken and then marked into columns

,transID,abrasive cleaner,artif. sweetener,baby cosmetics,baby food,bags,baking powder,bathroom cleaner,beef,berries,...,UHT-milk,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [7]:
df1.shape

# 9835 shopping carts are analyzed with 169 unique items as one is id

(9835, 170)

In [8]:
df1.dtypes

transID             int64
abrasive cleaner    int64
artif. sweetener    int64
baby cosmetics      int64
baby food           int64
                    ...
white bread         int64
white wine          int64
whole milk          int64
yogurt              int64
zwieback            int64
Length: 170, dtype: object

In [9]:
df1.drop('transID', inplace = True, axis = 1)

# EDA

In [12]:
#columnwise sum
# this will give how many people purchaseed the item 
df1.sum(axis=0)

abrasive cleaner      35
artif. sweetener      32
baby cosmetics         6
baby food              1
bags                   4
                    ...
white bread          414
white wine           187
whole milk          2513
yogurt              1372
zwieback              68
Length: 169, dtype: int64

In [14]:
df1.sum(axis=0).sort_values(ascending=False)
#so this are the best seeling items

whole milk               2513
other vegetables         1903
rolls/buns               1809
soda                     1715
yogurt                   1372
                         ...
kitchen utensil             4
bags                        4
preservation products       2
sound storage medium        1
baby food                   1
Length: 169, dtype: int64

In [15]:
top_20_items=df1.sum(axis=0).sort_values(ascending=False).head(20)

In [16]:
top_20_items

whole milk               2513
other vegetables         1903
rolls/buns               1809
soda                     1715
yogurt                   1372
bottled water            1087
root vegetables          1072
tropical fruit           1032
shopping bags             969
sausage                   924
pastry                    875
citrus fruit              814
bottled beer              792
newspapers                785
canned beer               764
pip fruit                 744
fruit/vegetable juice     711
whipped/sour cream        705
brown bread               638
domestic eggs             624
dtype: int64

In [19]:
df2=df1.copy(deep=True)
df2=df2.astype(bool)
df2.head()
#astype cannot be used if there is any missng values in that partpcular columns or dataframe

,abrasive cleaner,artif. sweetener,baby cosmetics,baby food,bags,baking powder,bathroom cleaner,beef,berries,beverages,...,UHT-milk,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False

In [20]:
df2.dtypes

abrasive cleaner    bool
artif. sweetener    bool
baby cosmetics      bool
baby food           bool
bags                bool
                    ...
white bread         bool
white wine          bool
whole milk          bool
yogurt              bool
zwieback            bool
Length: 169, dtype: object

# Building Association Rules

You will need a call to two functions:
- The first will identify *frequent itemsets*, in other words, sets that meet a specified support threshold
- The second will build *association rules* that meet a specified lift (alternatively, confidence) threshold

Note that there may be no rules that meet the specified threshold. In this case, the threshold value will need to be reduced.

In [27]:
# used to find popular items
apriori(df2, min_support = 0.01, use_colnames = True)
#here support value gives how many people have bought thse items 
# min-support means pick the most frequent products having popularity more than 1%

      support                                       itemsets
0    0.017692                                (baking powder)
1    0.052466                                         (beef)
2    0.033249                                      (berries)
3    0.026029                                    (beverages)
4    0.080529                                 (bottled beer)
..        ...                                            ...
328  0.011998  (tropical fruit, whole milk, root vegetables)
329  0.014540          (whole milk, yogurt, root vegetables)
330  0.010473                     (soda, whole milk, yogurt)
331  0.015150           (tropical fruit, whole milk, yogurt)
332  0.010880       (whipped/sour cream, whole milk, yogurt)

[333 rows x 2 columns]

In [24]:
#find the items which are popular items with popularity greater than 1%
frequent_itemsets = apriori(df2, min_support = 0.01, use_colnames = True)


# min-support means pick the most frequent products having popularity more than 1% and use column names
# is used because we want to show column names also

In [28]:
#finding strong assocations on the popular items slected using the lift or support

In [25]:
rules=association_rules(frequent_itemsets,metric='lift')

In [26]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(beef),(other vegetables),0.052466,0.193493,0.019725,0.375969,1.943066,0.009574,1.292416,0.512224
1,(other vegetables),(beef),0.193493,0.052466,0.019725,0.101944,1.943066,0.009574,1.055095,0.601792
2,(rolls/buns),(beef),0.183935,0.052466,0.013625,0.074074,1.411858,0.003975,1.023337,0.357463
3,(beef),(rolls/buns),0.052466,0.183935,0.013625,0.259690,1.411858,0.003975,1.102329,0.307866
4,(beef),(root vegetables),0.052466,0.108998,0.017387,0.331395,3.040367,0.011668,1.332628,0.708251
...,...,...,...,...,...,...,...,...,...,...
611,"(whipped/sour cream, yogurt)",(whole milk),0.020742,0.255516,0.010880,0.524510,2.052747,0.005580,1.565719,0.523711
612,"(whole milk, yogurt)",(whipped/sour cream),0.056024,0.071683,0.010880,0.194192,2.709053,0.006864,1.152033,0.668309
613,(whipped/sour cream),"(whole milk, yogurt)",0.071683,0.056024,0.010880,0.151773,2.709053,0.006864,1.112881,0.679582
614,(whole milk),"(whipped/sour cream, yogurt)",0.255516,0.020742,0.010880,0.042579,2.052747,0.005580,1.022807,0.688864
615,(yogurt),"(whipped/sour cream, whole milk)",0.139502,0.032232,0.010880,0.077988,2.419607,0.006383,1.049627,0.681826

In [29]:
#antecendnts has all popular items and in consequents the associated items are mentione

In [30]:
# if lift value is 1 then it means there is no assocaition and it is just because by chance ,
# lift less than 1 means this items are never purchased/
#lift greater than means itesm were purchased togetehr